foreach (max_year RANGE 2014 2030)
    set(max_sdk "$ENV{ADSK_3DSMAX_SDK_${max_year}}")
    if (NOT "${max_sdk}" STREQUAL "")
        MESSAGE(STATUS "Autodesk 3ds Max SDK found at ${max_sdk}")
        set(HAS_MAX TRUE)
    endif ()
endforeach ()

if (${HAS_MAX})
    OPTION(BUILD_IFCMAX "Build IfcMax, a 3ds Max plug-in, Windows-only." OFF)
endif()

IF(NOT MINIMAL_BUILD AND BUILD_IFCMAX)
    ADD_SUBDIRECTORY(../src/ifcmax ifcmax)
ENDIF()
