CONDA_BUILD_SYSROOT: # used for github actions conda daily build
  - /Users/runner/work/MacOSX10.15.sdk       # [osx]

occt:
  - 7.7.1

cgal-cpp:
  - 5.3

c_compiler:
  - vs2022  # [win]

cxx_compiler:
  - vs2022  # [win]