CONDA_BUILD_SYSROOT: # used for github actions conda daily build
  - /Users/runner/work/osx-sdk/MacOSX10.15.sdk       # [osx]

occt:
  - 7.7.1

c_compiler:
  - vs2022  # [win]

cxx_compiler:
  - vs2022  # [win]