context:
  name: nano-ifc
  version: 0.0.1

package:
  name: '{{ name|lower }}'
  version: '{{ version }}'

source:
  path: ../

build:
  number: 1
  script: python -m pip install . --no-build-isolation -v

requirements:
  run_exports:
    strong:
      - occt

  build:
    - "{{ compiler('c') }}"
    - "{{ compiler('cxx') }}"
    - sel(unix): "{{ cdt('mesa-libGL-devel') }}"  # provides OpenGL development libraries
    - pip
    - scikit-build-core
    - nanobind

  host:
    - python
    - occt {{ occt }}
    - cgal-cpp

  run:
    - python
    - occt {{ occt }}
    - cgal-cpp

test:
  source_files:
    - tests
  requires:
    - pytest
    - occt {{ occt }}
  commands:
    - pytest tests

about:
  home: https://github.com/Krande/adacpp
  license: "GPL-3.0-or-later"
  license_family: GPL3
  summary: "A module with drop-in replacement functions for ada-py written in c++ to improve performance."

extra:
  recipe-maintainers:
    - Krande