name: Publish IfcOpenShell-dev

on: 
  push:

jobs:
  activate:
    runs-on: ubuntu-latest
    if: github.repository == 'krande/IfcOpenShell'
    steps:
    - name: Set env
      run: echo ok go

  build:
    runs-on: windows-latest
    needs: activate
    env:
      IFCOS_INSTALL_PYTHON: TRUE
      TARGET_ARCH: x64
    steps:
    - uses: actions/checkout@v2
    - uses: ilammy/msvc-dev-cmd@v1
    - uses: conda-incubator/setup-miniconda@v2
      with:
        auto-activate-base: true
        auto-update-conda: true
        python-version: 3.8
    - name: Test Conda on path
      run: conda list
    - name: Update Submodules
      run: |
        git submodule init
        git submodule update
    - name: Config Conda Env
      run: |
        conda config --set always_yes yes --set changeps1 no
        conda update -q conda
        conda info -a
        conda config --add channels https://conda.anaconda.org/conda-forge
    - name: Create Anaconda env
      run: conda create --yes --quiet --name build_env conda-build=3.16.3 conda-verify libarchive python=3.8 anaconda-client=1.7.2
    - name: Make Conda Package
      run: |
        source activate build_env
        conda config --set anaconda_upload yes
        conda build --no-remove-work-dir --dirty --token ${{secrets.CONDATOKEN}} --user krande -c krande conda
