name: ci-ifcopenshell-conda-daily

on:
  push:
      paths:
        - .github/workflows/ci-ifcopenshell-conda-daily.yml
        - conda/**
  schedule:
  #         ┌───────────── minute (0 - 59)
  #         │  ┌───────────── hour (0 - 23)
  #         │  │ ┌───────────── day of the month (1 - 31)
  #         │  │ │ ┌───────────── month (1 - 12 or JAN-DEC)
  #         │  │ │ │ ┌───────────── day of the week (0 - 6 or SUN-SAT)
  #         *  * * * *
  - cron: "49 23 * * *" # 11min before utc midnight every day

jobs:
  test:
    name: ${{ matrix.platform.distver }}-${{ matrix.pyver.name }}
    runs-on: ${{ matrix.platform.distver }}
    defaults:
      run:
        shell: bash -l {0}
    strategy:
      fail-fast: false
      matrix:
        pyver: [
#          { name: py310, distver: '3.10'},
          { name: py311, distver: '3.11'}
        ]
        platform: [
          { name: Windows, distver: windows-2022, upload: 'true' },
          { name: Linux, distver: ubuntu-22.04,  upload: 'true' },
          { name: macOS, distver: macos-12, upload: 'true' }
        ]
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: uninstall swig on linux (which for some reason overrides conda build swig)
        if: ${{ matrix.platform.name == 'Linux' }}
        run: |
          sudo apt-get remove swig
          
      - name: Download MacOSX SDK
        if: ${{ matrix.platform.name == 'macOS' }}
        run: |
          curl -L https://github.com/phracker/MacOSX-SDKs/releases/download/11.3/MacOSX10.15.sdk.tar.xz | tar -xvJf - -C /Users/runner/work/

      - uses: mamba-org/setup-micromamba@v1 # https://github.com/mamba-org/setup-micromamba
        with:
          environment-file: conda/environment.yml
          create-args: >-
            python=${{ matrix.pyver.distver }}

      - name: build & test package
        run: |
          mkdir -p ${{ github.workspace }}/dist
          boa build conda --python ${{ matrix.pyver.distver }} -m ./conda/conda_build_config.yaml --no-remove-work-dir --output-folder '${{ github.workspace }}/dist'

      - name: upload to anaconda
        if: matrix.platform.upload == 'true'
        run: |
          path="${{ github.workspace }}/dist/${{ matrix.platform.pkg_dir }}/*.tar.bz2"
          if [ "${{ matrix.platform.name }}" == 'Windows' ]; then
            path="'$path'"
          fi
          anaconda -t ${{ secrets.ANACONDA_TOKEN }} upload --force --user krande --label dev $path
